baseURL = 'https://uraot.github.io/blog/'
languageCode = 'ja'
title = '閑話'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = 'production'
  title = '閑話'
  description = "理工系大学生の技術メモと日常の記録"
  keywords = [ "Blog", "Tech", "Life", "Engineering" ]
  author = "Me"
  defaultTheme = "auto" # dark, light, auto
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    disableHLJS = false # set true to use Prism.js
    favicon = "<link / abs url>"
    favicon16x16 = "<link / abs url>"
    favicon32x32 = "<link / abs url>"
    apple_touch_icon = "<link / abs url>"
    safari_pinned_tab = "<link / abs url>"

  [params.label]
    text = "Home"
    icon = ""
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "閑話"
    subtitle = "雑記帳"
    imageUrl = ""
    imageWidth = 120
    imageHeight = 120
    imageTitle = "My Profile"
    buttons = [
      { name = "Tech", url = "tech" },
      { name = "Life", url = "life" },
      { name = "About", url = "about" },
      { name = "GitHub", url = "https://github.com/uraoz" },
    ]

  [params.homeInfoParams]
    Title = "Welcome"
    Content = "技術的なことや日々の生活について書いていきます。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/uraoz"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/uraoz"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/xia0sen/"

    [[params.socialIcons]]
    name = "discord"
    url = "https://discordapp.com/users/370728847206907909"

[menu]
  [[menu.main]]
    identifier = "tech"
    name = "Tech"
    url = "/tech/"
    weight = 10
  [[menu.main]]
    identifier = "life"
    name = "Life"
    url = "/life/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

# MathJax support
[params.math]
  enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'monokai'
